services:
  app:
    image: serversideup/php:8.3-fpm-nginx
    container_name: cerdas-backend
    ports:
      - "9980:8080"
    volumes:
      - ./:/var/www/html
    environment:
      - PUID=1000
      - PGID=1000
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_KEY=${APP_KEY}
      - XDEBUG_MODE=off
      - PHP_OPCACHE_ENABLE=1
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: mariadb:10.11
    container_name: cerdas-db
    ports:
      - "33066:3306" # Expose on different port to avoid XAMPP conflict
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cerdas
      - MYSQL_USER=cerdas
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
